import electricGuitar from './instrumentIcons/electric-guitar.png';
import piano from './instrumentIcons/piano.png';
import drums from './instrumentIcons/drumset.png'
import bassGuitar from './instrumentIcons/bass-guitar.png';
import trumpet from './instrumentIcons/trumpet.png';
import violin from './instrumentIcons/violin.png';
import harmonica from './instrumentIcons/harmonica.png';
import saxophone from './instrumentIcons/saxophone.png';
import trombone from './instrumentIcons/trombone.png';
import percussion from './instrumentIcons/percussion.png';
import acousticGuitar from './instrumentIcons/acoustic-guitar.png';
import contrabass from './instrumentIcons/contrabass.png';
import flute from './instrumentIcons/flute.png';
import cello from './instrumentIcons/cello.png';
import accordion from './instrumentIcons/accordion.png';

const instruments = {
  'Electric-guitar': electricGuitar,
  'Piano': piano,
  'Drums': drums,
  'Bass': bassGuitar,
  'Trumpet': trumpet,
  'Violin': violin,
  'Harmonica': harmonica,
  'Saxophone': saxophone,
  'Trombone': trombone,
  'Percussion': percussion,
  'Acoustic-guitar': acousticGuitar,
  'Contrabass': contrabass,
  'Flute': flute,
  'Cello': cello,
  'Accordion': accordion
};

const skillLevels = ['Beginner', 'Intermediate', 'Advance', 'Professional']

const lookingFor = ['Bands', 'Jams', 'Song writing', 'Studio work']

const citiesInFinland = ['Äänekoski',
  'Åbo,',
  'Ackas',
  'Ähtäri',
  'Akaa',
  'Alajärvi',
  'Alavo',
  'Alavus',
  'Björneborg',
  'Borgå',
  'Brahestad',
  'Esbo',
  'Espoo',
  'Etseri',
  'Forssa',
  'Fredrikshamn',
  'Grankulla ',
  'Haapajärvi',
  'Haapavesi',
  'Hämeenlinna',
  'Hamina',
  'Hangö',
  'Hanko',
  'Harjavalta',
  'Heinola',
  'Helsingfors',
  'Helsinki',
  'Högfors',
  'Huittinen',
  'Hyvinge',
  'Hyvinkää',
  'Idensalmi',
  'Iisalmi',
  'Ikaalinen',
  'Ikalis',
  'Imatra',
  'Jakobstad',
  'Jämsä',
  'Järvenpää',
  'Joensuu',
  'Jyväskylä',
  'Kaarina',
  'Kajaani',
  'Kajana',
  'Kalajoki',
  'Kangasala',
  'Kankaanpää',
  'Kannus',
  'Karkkila',
  'Karleby',
  'Kaskinen',
  'Kaskö',
  'Kauhajoki',
  'Kauhava',
  'Kauniainen',
  'Kemi',
  'Kemijärvi',
  'Kerava',
  'Kervo',
  'Keuru',
  'Keuruu',
  'Kides',
  'Kitee',
  'Kiuruvesi',
  'Kokemäki',
  'Kokkola',
  'Kotka',
  'Kouvola',
  'Kristiinankaupunki',
  'Kristinestad',
  'Kuhmo',
  'Kumo',
  'Kuopio',
  'Kurikka',
  'Kuusamo',
  'Lahti',
  'Lahtis',
  'Laitila',
  'Lappeenranta',
  'Lappo',
  'Lapua',
  'Letala',
  'Lieksa',
  'Lohja',
  'Loimaa',
  'Lojo',
  'Loviisa',
  'Lovisa',
  'Maarianhamina',
  'Mänttä-Vilppula',
  'Mariehamn',
  'Mikkeli',
  'Naantali',
  'Nådendal',
  'Nivala',
  'Nokia',
  'Nurmes',
  'Nykarleby',
  'Nyslott',
  'Nystad',
  'Orimattila',
  'Orivesi',
  'Oulainen',
  'Oulu',
  'Outokumpu',
  'Paimio',
  'Parainen',
  'Pargas',
  'Parkano',
  'Pemar',
  'Pieksämäki',
  'Pietarsaari',
  'Pori',
  'Porvoo',
  'Pudasjärvi',
  'Pyhäjärvi',
  'Raahe',
  'Raasepori',
  'Raisio',
  'Raseborg',
  'Rauma',
  'Raumo',
  'Reso',
  'Riihimäki',
  'Rovaniemi',
  'S:t Karins',
  'S:t Michel',
  'Saarijärvi',
  'Salo',
  'Sastamala',
  'Savonlinna',
  'Seinäjoki',
  'Somero',
  'Suonenjoki',
  'Tammerfors',
  'Tampere',
  'Tavastehus',
  'Torneå',
  'Tornio',
  'Träskända',
  'Turku',
  'Uleåborg',
  'Ulvila',
  'Ulvsby',
  'Uusikaarlepyy',
  'Uusikaupunki',
  'Vaasa',
  'Valkeakoski',
  'Vanda',
  'Vantaa',
  'Varkaus',
  'Vasa',
  'Viitasaari',
  'Villmanstrand',
  'Virdois',
  'Virrat',
  'Vittis',
  'Ylivieska',
  'Ylöjärvi'
]

export { instruments, skillLevels, lookingFor, citiesInFinland };